### ISSUE TITLE
has text relocations

### ISSUE THREAD

**Issue by wirteEable** [jzt-Tesla/GoogleSerialPort#1]
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/cn.humiao.myserialport-1/lib/arm/libserial_port.so: has text relocations
                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                                                       at java.lang.System.loadLibrary(System.java:1562)
                                                       at android_serialport_api.SerialPort.<clinit>(SerialPort.java:83)
                                                       at cn.humiao.myserialport.SerialPortUtil.openSerialPort(SerialPortUtil.java:34)
                                                       at cn.humiao.myserialport.MainActivity.onCreate(MainActivity.java:28)

**Comment by marvin-an** [comment]
> java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/cn.humiao.myserialport-1/lib/arm/libserial_port.so: has text relocations
> at java.lang.Runtime.loadLibrary0(Runtime.java:989)
> at java.lang.System.loadLibrary(System.java:1562)
> at android_serialport_api.SerialPort.(SerialPort.java:83)
> at cn.humiao.myserialport.SerialPortUtil.openSerialPort(SerialPortUtil.java:34)
> at cn.humiao.myserialport.MainActivity.onCreate(MainActivity.java:28)

我也是一样

**Comment by jzt-Tesla** [comment]
建议参考这篇文章：https://blog.csdn.net/l419070777/article/details/78590219，我本身项目的Android系统是4.4.4，而我的targetSdkVersion为26，你可以结合文章去找答案。

**Comment by TangJingWei** [comment]
文章找不到
